import type { WardrobePageData } from "@/types/wardrobe";

const baseItems: WardrobePageData["items"] = [
  {
    id: "w1",
    name: "White Linen Shirt",
    brand: "Uniqlo",
    category: "tops",
    color: "White",
    colorHex: "#f5f5f5",
    imageUrl:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=500&fit=crop",
    timesWorn: 12,
    lastWorn: "2 days ago",
    isFavorite: true,
    price: 2490,
    purchaseDate: "Mar 2025",
    fabric: "Linen",
    season: ["summer", "spring"],
    occasions: ["casual", "office"],
    fitNotes: "Relaxed fit — size M",
    aiCompatibilityScore: 94,
    addedAt: "2025-03-12",
  },
  {
    id: "w2",
    name: "Navy Oxford Shirt",
    brand: "Zara",
    category: "tops",
    color: "Navy",
    colorHex: "#1e3a5f",
    imageUrl:
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3b9a?w=400&h=500&fit=crop",
    timesWorn: 8,
    lastWorn: "1 week ago",
    isFavorite: false,
    price: 3290,
    fabric: "Cotton",
    season: ["all-season"],
    occasions: ["office"],
    aiCompatibilityScore: 88,
    addedAt: "2025-01-20",
  },
  {
    id: "w3",
    name: "Black Crew Tee",
    brand: "H&M",
    category: "tops",
    color: "Black",
    colorHex: "#1a1a1a",
    imageUrl:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=500&fit=crop",
    timesWorn: 24,
    lastWorn: "Yesterday",
    isFavorite: true,
    price: 799,
    fabric: "Cotton",
    season: ["all-season"],
    occasions: ["casual", "gym"],
    aiCompatibilityScore: 91,
    addedAt: "2024-11-05",
  },
  {
    id: "w4",
    name: "Dark Blue Jeans",
    brand: "Levi's",
    category: "bottoms",
    color: "Indigo",
    colorHex: "#2c3e6b",
    imageUrl:
      "https://images.unsplash.com/photo-1473966968600-fa801b068a0a?w=400&h=500&fit=crop",
    timesWorn: 18,
    lastWorn: "3 days ago",
    isFavorite: true,
    price: 4499,
    fabric: "Denim",
    season: ["all-season"],
    occasions: ["casual", "office"],
    aiCompatibilityScore: 96,
    addedAt: "2024-09-18",
  },
  {
    id: "w5",
    name: "Slim Chinos",
    brand: "Uniqlo",
    category: "bottoms",
    color: "Beige",
    colorHex: "#d4c4a8",
    imageUrl:
      "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400&h=500&fit=crop",
    timesWorn: 6,
    lastWorn: "5 days ago",
    isFavorite: false,
    price: 2990,
    season: ["spring", "autumn"],
    occasions: ["office", "casual"],
    aiCompatibilityScore: 85,
    addedAt: "2025-02-01",
  },
  {
    id: "w6",
    name: "White Sneakers",
    brand: "Nike",
    category: "shoes",
    color: "White",
    colorHex: "#f0f0f0",
    imageUrl:
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=500&fit=crop",
    timesWorn: 32,
    lastWorn: "Today",
    isFavorite: true,
    price: 7495,
    season: ["all-season"],
    occasions: ["casual", "travel"],
    aiCompatibilityScore: 97,
    addedAt: "2024-08-10",
  },
  {
    id: "w7",
    name: "Leather Loafers",
    brand: "Clarks",
    category: "shoes",
    color: "Brown",
    colorHex: "#5c4033",
    imageUrl:
      "https://images.unsplash.com/photo-1533867610405-41f91a92246a?w=400&h=500&fit=crop",
    timesWorn: 4,
    lastWorn: "2 weeks ago",
    isFavorite: false,
    price: 8999,
    season: ["all-season"],
    occasions: ["office", "wedding"],
    aiCompatibilityScore: 82,
    addedAt: "2025-04-22",
  },
  {
    id: "w8",
    name: "Minimal Watch",
    brand: "Fossil",
    category: "accessories",
    color: "Silver",
    colorHex: "#c0c0c0",
    imageUrl:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=500&fit=crop",
    timesWorn: 40,
    lastWorn: "Today",
    isFavorite: true,
    price: 12999,
    season: ["all-season"],
    occasions: ["office", "party"],
    aiCompatibilityScore: 90,
    addedAt: "2024-06-15",
  },
  {
    id: "w9",
    name: "Aviator Sunglasses",
    brand: "Ray-Ban",
    category: "accessories",
    color: "Gold",
    colorHex: "#d4af37",
    imageUrl:
      "https://images.unsplash.com/photo-1572635196233-14b250f6532c?w=400&h=500&fit=crop",
    timesWorn: 15,
    lastWorn: "4 days ago",
    isFavorite: false,
    season: ["summer"],
    occasions: ["casual", "travel"],
    addedAt: "2025-05-01",
  },
  {
    id: "w10",
    name: "Olive Bomber Jacket",
    brand: "Zara",
    category: "jackets",
    color: "Olive",
    colorHex: "#556b2f",
    imageUrl:
      "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=500&fit=crop",
    timesWorn: 5,
    lastWorn: "1 week ago",
    isFavorite: false,
    price: 5990,
    season: ["autumn", "spring"],
    occasions: ["casual"],
    addedAt: "2025-07-10",
  },
  {
    id: "w11",
    name: "Black Belt",
    brand: "H&M",
    category: "accessories",
    color: "Black",
    colorHex: "#1a1a1a",
    imageUrl:
      "https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=400&h=500&fit=crop",
    timesWorn: 22,
    lastWorn: "Yesterday",
    isFavorite: false,
    season: ["all-season"],
    occasions: ["office"],
    addedAt: "2024-10-02",
  },
  {
    id: "w12",
    name: "Grey Joggers",
    brand: "Nike",
    category: "bottoms",
    color: "Grey",
    colorHex: "#808080",
    imageUrl:
      "https://images.unsplash.com/photo-1506629082955-511b2aa2cefb?w=400&h=500&fit=crop",
    timesWorn: 10,
    lastWorn: "3 days ago",
    isFavorite: false,
    season: ["all-season"],
    occasions: ["gym", "casual"],
    addedAt: "2025-01-15",
  },
];

export const mockWardrobeData: WardrobePageData = {
  header: {
    title: "My Wardrobe",
    subtitle: "Everything you own, intelligently organized.",
  },
  overviewStats: [
    { id: "total", label: "Total Items", value: "128" },
    { id: "categories", label: "Categories", value: "12" },
    { id: "most-worn", label: "Most Worn", value: "White Shirt" },
    { id: "last-added", label: "Last Added", value: "Black Blazer" },
    {
      id: "health",
      label: "Wardrobe Health",
      value: "82%",
      progress: 82,
    },
  ],
  categories: [
    { id: "all", label: "All Items", count: 128 },
    { id: "tops", label: "Tops", count: 42 },
    { id: "bottoms", label: "Bottoms", count: 25 },
    { id: "dresses", label: "Dresses", count: 8 },
    { id: "shoes", label: "Shoes", count: 18 },
    { id: "jackets", label: "Jackets", count: 12 },
    { id: "accessories", label: "Accessories", count: 43 },
  ],
  seasons: [
    { id: "summer", label: "Summer" },
    { id: "winter", label: "Winter" },
    { id: "spring", label: "Spring" },
    { id: "autumn", label: "Autumn" },
    { id: "all-season", label: "All Season" },
  ],
  occasions: [
    { id: "casual", label: "Casual" },
    { id: "office", label: "Office" },
    { id: "wedding", label: "Wedding" },
    { id: "party", label: "Party" },
    { id: "travel", label: "Travel" },
    { id: "gym", label: "Gym" },
  ],
  colors: [
    { id: "black", label: "Black", hex: "#1a1a1a" },
    { id: "white", label: "White", hex: "#f5f5f5" },
    { id: "navy", label: "Navy", hex: "#1e3a5f" },
    { id: "beige", label: "Beige", hex: "#d4c4a8" },
    { id: "olive", label: "Olive", hex: "#556b2f" },
  ],
  sortOptions: [
    { id: "recent", label: "Recently Added" },
    { id: "most-worn", label: "Most Used" },
    { id: "favorites", label: "Favorites" },
    { id: "never-worn", label: "Never Worn" },
  ],
  items: baseItems,
  insights: [
    { id: "i1", label: "Most Worn Color", value: "Black" },
    { id: "i2", label: "Least Used Category", value: "Accessories" },
    { id: "i3", label: "Items Not Worn", value: "14" },
    { id: "i4", label: "Favorite Brand", value: "Uniqlo" },
  ],
  aiFeatures: [
    {
      id: "outfit",
      label: "Build Outfit",
      description: "Combine items into complete looks",
    },
    {
      id: "gaps",
      label: "Find Missing Pieces",
      description: "Discover wardrobe gaps",
    },
    {
      id: "rate",
      label: "Rate Wardrobe",
      description: "Get an AI style score",
    },
    {
      id: "pack",
      label: "Packing Assistant",
      description: "Smart travel packing lists",
    },
  ],
  addItemSteps: ["Upload", "Details", "Attributes", "Occasion", "Review"],
};
