import type { WardrobePageData } from "@/types/wardrobe";

export const mockWardrobeData: WardrobePageData = {
  stats: {
    totalItems: 128,
    tops: 42,
    bottoms: 25,
    shoes: 18,
    accessories: 43,
  },
  categories: [
    { id: "all", label: "All Items", count: 128 },
    { id: "tops", label: "Tops", count: 42 },
    { id: "bottoms", label: "Bottoms", count: 25 },
    { id: "shoes", label: "Shoes", count: 18 },
    { id: "accessories", label: "Accessories", count: 43 },
  ],
  items: [
    {
      id: "w1",
      name: "White Linen Shirt",
      brand: "Uniqlo",
      category: "tops",
      color: "White",
      colorHex: "#f5f5f5",
      imageUrl:
        "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=500&fit=crop",
      timesWorn: 12,
      lastWorn: "2 days ago",
    },
    {
      id: "w2",
      name: "Navy Oxford Shirt",
      brand: "Zara",
      category: "tops",
      color: "Navy",
      colorHex: "#1e3a5f",
      imageUrl:
        "https://images.unsplash.com/photo-1602810318383-e386cc2a3b9a?w=400&h=500&fit=crop",
      timesWorn: 8,
      lastWorn: "1 week ago",
    },
    {
      id: "w3",
      name: "Black Crew Tee",
      brand: "H&M",
      category: "tops",
      color: "Black",
      colorHex: "#1a1a1a",
      imageUrl:
        "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=500&fit=crop",
      timesWorn: 24,
      lastWorn: "Yesterday",
    },
    {
      id: "w4",
      name: "Dark Blue Jeans",
      brand: "Levi's",
      category: "bottoms",
      color: "Indigo",
      colorHex: "#2c3e6b",
      imageUrl:
        "https://images.unsplash.com/photo-1473966968600-fa801b068a0a?w=400&h=500&fit=crop",
      timesWorn: 18,
      lastWorn: "3 days ago",
    },
    {
      id: "w5",
      name: "Slim Chinos",
      brand: "Uniqlo",
      category: "bottoms",
      color: "Beige",
      colorHex: "#d4c4a8",
      imageUrl:
        "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=400&h=500&fit=crop",
      timesWorn: 6,
      lastWorn: "5 days ago",
    },
    {
      id: "w6",
      name: "White Sneakers",
      brand: "Nike",
      category: "shoes",
      color: "White",
      colorHex: "#f0f0f0",
      imageUrl:
        "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=500&fit=crop",
      timesWorn: 32,
      lastWorn: "Today",
    },
    {
      id: "w7",
      name: "Leather Loafers",
      brand: "Clarks",
      category: "shoes",
      color: "Brown",
      colorHex: "#5c4033",
      imageUrl:
        "https://images.unsplash.com/photo-1533867610405-41f91a92246a?w=400&h=500&fit=crop",
      timesWorn: 4,
      lastWorn: "2 weeks ago",
    },
    {
      id: "w8",
      name: "Minimal Watch",
      brand: "Fossil",
      category: "accessories",
      color: "Silver",
      colorHex: "#c0c0c0",
      imageUrl:
        "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=500&fit=crop",
      timesWorn: 40,
      lastWorn: "Today",
    },
    {
      id: "w9",
      name: "Aviator Sunglasses",
      brand: "Ray-Ban",
      category: "accessories",
      color: "Gold",
      colorHex: "#d4af37",
      imageUrl:
        "https://images.unsplash.com/photo-1572635196233-14b250f6532c?w=400&h=500&fit=crop",
      timesWorn: 15,
      lastWorn: "4 days ago",
    },
    {
      id: "w10",
      name: "Olive Bomber Jacket",
      brand: "Zara",
      category: "tops",
      color: "Olive",
      colorHex: "#556b2f",
      imageUrl:
        "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&h=500&fit=crop",
      timesWorn: 5,
      lastWorn: "1 week ago",
    },
    {
      id: "w11",
      name: "Black Belt",
      brand: "H&M",
      category: "accessories",
      color: "Black",
      colorHex: "#1a1a1a",
      imageUrl:
        "https://images.unsplash.com/photo-1624222247344-550fb60583fd?w=400&h=500&fit=crop",
      timesWorn: 22,
      lastWorn: "Yesterday",
    },
    {
      id: "w12",
      name: "Grey Joggers",
      brand: "Nike",
      category: "bottoms",
      color: "Grey",
      colorHex: "#808080",
      imageUrl:
        "https://images.unsplash.com/photo-1506629082955-511b2aa2cefb?w=400&h=500&fit=crop",
      timesWorn: 10,
      lastWorn: "3 days ago",
    },
  ],
};
